# Auth with polkit-gnome:
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1


# Import env vars for user systemd service manager
exec_always systemctl --user import-environment XDG_CURRENT_DESKTOP XDG_SESSION_TYPE DISPLAY WAYLAND_DISPLAY SWAYSOCK

# Update dbus environments with display variables
exec_always hash dbus-update-activation-environment 2>/dev/null && \
    dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP XDG_SESSION_TYPE DISPLAY WAYLAND_DISPLAY SWAYSOCK

# Autotiling
exec autotiling

# OSD
exec swayosd-server

# Idle manager
#
# Managed by the user systemd service in ~/.config/systemd/user/swayidle.service.
exec systemctl --user start swayidle.service

# 1Password
exec /usr/bin/1password --silent

# Output profile daemon
#
# Start kanshi once per Sway session. `exec_always` will spawn another daemon on
# every `sway reload`, which can lead to inconsistent output application.
exec kanshi

# Start on workspace 1
exec_always swaymsg workspace 1
