[metadata]
name = "alias"
description = "A channel to select from shell aliases"

[source]
# you may need to adjust the command depending on your shell
command = "$SHELL -ic 'alias'"
output = "{split:=:0}"

[preview]
command = "$SHELL -ic 'alias' | awk -F= -v name='{split:=:0}' '$1 == name { print }'"

[ui.preview_panel]
size = 30
