return {
  buffers = require(... .. ".buffers"),
  diagnostics = require(... .. ".diagnostics"),
  general = require(... .. ".general"),
  git = require(... .. ".git"),
  grug = require(... .. ".grugfar"),
  harpoon = require(... .. ".harpoon"),
  lsp = require(... .. ".lsp"),
  neotest = require(... .. ".neotest"),
  navigation = require(... .. ".navigation"),
  plugins = require(... .. ".plugins"),
  splits = require(... .. ".splits"),
  telescope = require(... .. ".telescope"),
  toggle = require(... .. ".toggle"),
}
