return {
  buffers = require(... .. ".buffers"),
  ai = require(... .. ".ai"),
  general = require(... .. ".general"),
  git = require(... .. ".git"),
  grug = require(... .. ".grugfar"),
  grapple = require(... .. ".grapple"),
  lsp = require(... .. ".lsp"),
  neotest = require(... .. ".neotest"),
  navigation = require(... .. ".navigation"),
  plugins = require(... .. ".plugins"),
  splits = require(... .. ".splits"),
  telescope = require(... .. ".telescope"),
  toggle = require(... .. ".toggle"),
}
