model = "gpt-5.4"
model_reasoning_effort = "medium"
personality = "pragmatic"

[projects."/Users/john.enderby"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/personal/dots"]
trust_level = "trusted"

[projects."/Users/john.enderby/.cursor"]
trust_level = "trusted"

[projects."/home/johne"]
trust_level = "trusted"

[projects."/home/johne/Developer/dots"]
trust_level = "trusted"

[projects."/home/johne/Developer/the-future"]
trust_level = "trusted"

[projects."/home/johne/Documents/Obsidian"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/fanduel/raccoons/aw-dynamic-web"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/fanduel/raccoons/account_e2e_cypress"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/fanduel/raccoons/refer-a-friend-service"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/fanduel/raccoons/raf-app"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/fanduel/sportsbook"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[tui]
theme = "catppuccin-mocha"
