model = "gpt-5.4"
model_reasoning_effort = "medium"

[projects."/Users/john.enderby"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/personal/dots"]
trust_level = "trusted"

[projects."/home/johne"]
trust_level = "trusted"

[projects."/home/johne/Developer/dots"]
trust_level = "trusted"

[projects."/home/johne/Developer/the-future"]
trust_level = "trusted"

[projects."/home/johne/Documents/Obsidian"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
