model = "gpt-5.5"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
plan_mode_reasoning_effort = "xhigh"

[projects."/Users/john.enderby"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/personal/dots"]
trust_level = "trusted"

[projects."/Users/john.enderby/.cursor"]
trust_level = "trusted"

[projects."/home/johne"]
trust_level = "trusted"

[projects."/home/johne/Developer/dots"]
trust_level = "trusted"

[projects."/home/johne/Developer/the-future"]
trust_level = "trusted"

[projects."/home/johne/Documents/Obsidian"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/fanduel/raccoons/aw-dynamic-web"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/fanduel/raccoons/account_e2e_cypress"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/fanduel/raccoons/refer-a-friend-service"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/fanduel/raccoons/raf-app"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/fanduel/sportsbook"]
trust_level = "trusted"

[projects."/Users/john.enderby/Developer/fanduel/ten-percent/level-up-butler"]
trust_level = "trusted"

[projects."/home/johne/Developer/startpage"]
trust_level = "trusted"

[projects."/home/johne/Developer/aurijin"]
trust_level = "trusted"

[projects."/home/johne/Developer/dots/common/.config/nvim"]
trust_level = "trusted"

[projects."/home/johne/Developer"]
trust_level = "trusted"

[projects."/home/johne/Developer/dots/common/.config/tmux"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
"gpt-5.4" = "gpt-5.5"

[tui]
theme = "catppuccin-mocha"
vim_mode_default = true
status_line = ["model-with-reasoning", "current-dir", "project-name", "git-branch", "context-used", "codex-version", "context-window-size"]

[tui.model_availability_nux]
"gpt-5.5" = 4

[[skills.config]]
path = "/home/johne/Developer/dots/common/.ai/skills/audit-claude-setup/SKILL.md"
enabled = false
