[colors]
# Regular colors
background = '#11111b'
foreground  = '#cdd6f4'
black = '#11111b'
blue = '#89b4fa'
cyan = '#74c7ec'
green = '#a6e3a1'
magenta = '#cba6fb'
red = '#f38ba8'
white = '#bac2de'
yellow = '#f9e2af'

# Cursor
cursor = '#F712FF'
vi-cursor = '#12d0ff'

# Navigation
tabs = '#cba6fb'
tabs-foreground = '#bac2de'
tabs-active = '#11111b'
tabs-active-highlight = '#cba6fb'
tabs-active-foreground = '#cdd6f4'
bar = '#1e1e2e'

# Search
search-match-background = '#89b4fa'
search-match-foreground = '#11111b'
search-focused-match-background = '#f9e2af'
search-focused-match-foreground = '#11111b'

# Selection
selection-foreground = '#11111b'
selection-background = '#cba6fb'

# Dim colors
dim-black = '#1C191A'
dim-blue = '#8caaee'
dim-cyan = '#85c1dc'
dim-foreground = '#a6adc8'
dim-green = '#a6d189'
dim-magenta = '#ca9ee6'
dim-red = '#e78284'
dim-white = '#bac2de'
dim-yellow = '#e5c890'

# Light colors
light-black = '#1e1e2e'
light-blue = '#89b4fa'
light-cyan = '#74c7ec'
light-foreground = '#cdd6f4'
light-green = '#a6e3a1'
light-magenta = '#cba6fb'
light-red = '#f38ba8'
light-white = '#bac2de'
light-yellow = '#f9e2af'
