[tools]
node = "lts"
pnpm = "11"
zig = "latest"
go = "latest"
yarn = "1.22"
bun = "latest"
deno = "latest"

# Mac only
java = {version = "corretto-21.0.6.7.1", os = ["macos"]}
ruby = {version = "3.4.5", os = ["macos"]}

# Linux only
codex = {version = "latest", os = ["linux"]}
