[colors.primary]
background = "#11111b"
foreground = "#cdd6f4"
dim_foreground = "#cdd6f4"
bright_foreground = "#11111b"

[colors.cursor]
text = "#1e1e2e"
cursor = "#D20F39"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#fe640b"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#cba6fb"

[colors.normal]
black = "#11111b"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6fb"
cyan = "#74c7ec"
white = "#cdd6f4"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6fb"
cyan = "#74c7ec"
white = "#a6ADC8"

[colors.dim]
black = "#1e1e2e"
red = "#e68284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#ca9ee6"
cyan = "#99d1db"
white = "#c6d0f5"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
