# alacritty.toml config
live_config_reload = true

import = [
  "~/.config/alacritty/catppuccin-mocha-dark.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"

[window]
decorations = 'Buttonless'
dynamic_padding = false
dynamic_title = true
opacity = 1
title = ''

[window.dimensions]
columns = 100
lines = 32

[window.padding]
x = 8
y = 8

[scrolling]
history = 12000

[font]
size = 14
glyph_offset = {x = 0, y = 0}

[font.normal]
family = "RecMonoLinear Nerd Font Mono"
style = "Regular"

[font.bold]
family = "RecMonoLinear Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "RecMonoCasual Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "RecMonoCasual Nerd Font Mono"
style = "Italic"
