-- Highlights that benefit make sense to have transparency
local M = {}

M.default = {
  "Normal",
  "NormalNC",
  "NormalFloat",
  "FloatBorder",
  "Pmenu",
  "Terminal",
  "EndOfBuffer",
  "FoldColumn",
  "Folded",
  "SignColumn",
  "NeoTreeNormal",
  "NeoTreeNormalNC",
  "NeoTreeVertSplit",
  "NeoTreeWinSeparator",
  "NeoTreeEndOfBuffer",
}

M.preserve_fg_highlights = {
  "GitSignsAdd",
  "GitSignsChange",
  "GitSignsDelete",
  "GitSignsChangedelete",
  "GitSignsTopdelete",
  "GitSignsUntracked",
  "GitSignsAddNr",
  "GitSignsChangeNr",
  "GitSignsDeleteNr",
  "GitSignsChangedeleteNr",
  "GitSignsTopdeleteNr",
  "GitSignsUntrackedNr",
  "GitSignsAddLn",
  "GitSignsChangeLn",
  "GitSignsChangedeleteLn",
  "GitSignsTopdeleteLn",
  "GitSignsUntrackedLn",
  "GitSignsAddCul",
  "GitSignsChangeCul",
  "GitSignsDeleteCul",
  "GitSignsChangedeleteCul",
  "GitSignsTopdeleteCul",
  "GitSignsUntrackedCul",
  "GitSignsStagedAdd",
  "GitSignsStagedChange",
  "GitSignsStagedDelete",
  "GitSignsStagedChangedelete",
  "GitSignsStagedTopdelete",
  "GitSignsStagedUntracked",
  "GitSignsStagedAddNr",
  "GitSignsStagedChangeNr",
  "GitSignsStagedDeleteNr",
  "GitSignsStagedChangedeleteNr",
  "GitSignsStagedTopdeleteNr",
  "GitSignsStagedUntrackedNr",
  "GitSignsStagedAddLn",
  "GitSignsStagedChangeLn",
  "GitSignsStagedChangedeleteLn",
  "GitSignsStagedTopdeleteLn",
  "GitSignsStagedUntrackedLn",
  "GitSignsStagedAddCul",
  "GitSignsStagedChangeCul",
  "GitSignsStagedDeleteCul",
  "GitSignsStagedChangedeleteCul",
  "GitSignsStagedTopdeleteCul",
  "GitSignsStagedUntrackedCul",
  "GitSignsAddPreview",
  "GitSignsDeletePreview",
  "GitSignsNoEOLPreview",
  "GitSignsCurrentLineBlame",
  "GitSignsAddInline",
  "GitSignsDeleteInline",
  "GitSignsChangeInline",
  "GitSignsAddLnInline",
  "GitSignsChangeLnInline",
  "GitSignsDeleteLnInline",
  "GitSignsDeleteVirtLn",
  "GitSignsDeleteVirtLnInLine",
  "GitSignsVirtLnum",
}

return M
